#!/usr/bin/env ruby

HELP = "RALIS 0.1, a RESTful API web framework.
Usage: ralis COMMAND [ARGS]

The most common ralis commands are:
 start       Starts the Ralis server
 stop        Stops the Ralis server

"

class AppLauncher
    def self.start
        output = `nginx -p \`pwd\`/ -c config/nginx.conf`
        raise output unless $? == 0
        puts "App was succesfully started."
    end

    def self.stop
        output = `nginx -s stop -p \`pwd\`/ -c config/nginx.conf`
        raise output unless $? == 0
        puts "App was succesfully stopped."
    end
end

class SpecHelper
    def self.spec(test)
        case test
        when 'core' then core
        else puts "Supported test types are: core."
        end
    end

    def self.core
        puts `busted spec/core`
    end
end


case ARGV[0]
when 'start' then AppLauncher.start
when 'stop' then AppLauncher.stop
when 'spec' then SpecHelper.spec(ARGV[1])
else puts HELP
end
