#!/usr/bin/env ruby

require './cli/ralis_launcher'

HELP = "RALIS v0.1, a RESTful API web framework.
Usage: ralis COMMAND [ARGS]

The most common ralis commands are:
 start       Starts the Ralis server
 stop        Stops the Ralis server

"

case ARGV[0]
when 'start' then Ralis::Launcher.start
when 'stop' then Ralis::Launcher.stop
else puts HELP
end
